### ISSUE TITLE
Max retries exceeded error

### ISSUE THREAD

**Issue by MatthiasDE** [MatthiasDE/ProductPriceMonitor.py#3]
**Describe the bug**

**To Reproduce**
1. Run the gather data container as daemon for some days (2021-09-27 10:51 - 2021-10-01 12:41 => 4d 2h)
2. Container is finished
3. docker container logs <container-name> shows following error
`INFO: Collection of data was finished at 2021-10-01 12:41:03.517882
INFO: Next data collection will run in 3 hours..
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.heise.de', port=443): Max retries exceeded with url: /preisvergleich/?cat=gra16_512&v=l&hloc=at&hloc=de&sort=r&bl1_id=30&xf=545_ASRock~545_ASUS~545_ATI~545_EVGA~545_GIGABYTE~545_MSI~545_NVIDIA~545_Sapphire~9810_06+16+-+RTX+3060 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1799ce14c0>: Failed to establish a new connection: [Errno -3] Try again'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/app/./PPM-DSC-HeisePV-GCM.py", line 216, in <module>
    product_dict = get_model_price_data(url)
  File "/usr/src/app/./PPM-DSC-HeisePV-GCM.py", line 52, in get_model_price_data
    r = requests.get(url, headers=requests_header_dict)
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.heise.de', port=443): Max retries exceeded with url: /preisvergleich/?cat=gra16_512&v=l&hloc=at&hloc=de&sort=r&bl1_id=30&xf=545_ASRock~545_ASUS~545_ATI~545_EVGA~545_GIGABYTE~545_MSI~545_NVIDIA~545_Sapphire~9810_06+16+-+RTX+3060 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f1799ce14c0>: Failed to establish a new connection: [Errno -3] Try again'))`

**Expected behavior**
Info for error but don't exist hard

**Comment by MatthiasDE** [comment]
Try to use the docker restart policy to restart the container in case of an issue:
`docker run -d --restart unless-stopped -v ~:/usr/src/app/db --entrypoint python ppm-dsc-hpv-gcm.py ./PPM-DSC-HeisePV-GCM.py -f ./db/product_price_monitor.db -r 3`, or - to be tested - might be better approach: `docker run -d --restart on-failure -v ~:/usr/src/app/db --entrypoint python ppm-dsc-hpv-gcm.py ./PPM-DSC-HeisePV-GCM.py -f ./db/product_price_monitor.db -r 3`
